const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { SSHAuthServer } = require('../electron/ssh-auth.cjs');
const { RemoteConnection } = require('../electron/remote-connection.cjs');
const { PreviewResources, resourceResponse } = require('../electron/preview-resources.cjs');
const { FileOperations } = require('../electron/file-operations.cjs');
const { createSSHFixture } = require('./helpers/ssh-fixture.cjs');
const { ProjectGit, gitEnvironment } = require('../electron/project-git.cjs');
const execGit = require('node:util').promisify(require('node:child_process').execFile);

const integrationDir = path.resolve(__dirname, '..', 'integration');
const sshPath = process.platform === 'win32' ? path.join(process.env.SystemRoot || 'C:\\Windows', 'System32/OpenSSH/ssh.exe') : 'ssh';
const waitFor = async callback => { const started = Date.now(); while (Date.now() - started < 15000) { if (await callback()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Timed out waiting for SSH test'); };

test('native OpenSSH reuses host config, authenticates once and carries terminal plus file requests', { timeout: 30000 }, async t => {
  const fixture = await createSSHFixture();
  for (const args of [['init', '-b', 'main'], ['config', 'user.name', 'SSH Test'], ['config', 'user.email', 'test@example.invalid'], ['commit', '--allow-empty', '-m', 'SSH history']]) await execGit('git', ['-C', fixture.project, ...args], { env: gitEnvironment(), windowsHide: true });
  await fs.writeFile(path.join(fixture.project, 'git-status.txt'), 'untracked');
  const auth = await new SSHAuthServer().start();
  const events = []; let output = '';
  const project = { id: randomUUID(), kind: 'ssh', path: process.platform === 'win32' ? '/srv/fixture' : fixture.project, ssh: { host: 'fixture', configFile: fixture.configFile } };
  const connection = new RemoteConnection(project, { integrationDir, auth, sshPath, sessionKey: 'test-session-key', onEvent: event => events.push(event) });
  connection.onData(data => { output += data; });
  t.after(async () => { connection.close(); auth.close(); await fixture.close(); });
  await connection.ready;
  const gitReader = new ProjectGit(() => connection);
  assert.equal((await gitReader.read(project, 'status')).files[0].path, 'git-status.txt');
  const commits = (await gitReader.read(project, 'history', 0)).commits;
  assert.equal(commits[0].subject, 'SSH history');
  assert.equal((await gitReader.read(project, 'files', commits[0].hash)).total, 0);
  const listing = await connection.request('directory', { path: '', offset: 0 });
  assert.equal(listing.path, '');
  await waitFor(() => events.some(event => event.type === 'shell-prompt'));
  connection.write('printf "SSH_TRANSPORT_OK\\n"\r');
  await waitFor(() => output.includes('SSH_TRANSPORT_OK'));
  connection.resize(110, 34);
  const imageBytes = await fs.readFile(path.join(__dirname, '..', 'assets/icon.png'));
  await fs.writeFile(path.join(fixture.project, '图片.png'), imageBytes);
  const resources = new PreviewResources({ remote: () => connection });
  const preview = resources.open(project, '图片.png', 'image', 'image/png');
  const resource = await resources.resolve(preview.url);
  const response = resourceResponse(resource, new Request(preview.url));
  assert.deepEqual(Buffer.from(await response.arrayBuffer()), imageBytes);
  const tail = resourceResponse(resource, new Request(preview.url, { headers: { Range: 'bytes=100-' } }));
  assert.equal(tail.status, 206);
  assert.deepEqual(Buffer.from(await tail.arrayBuffer()), imageBytes.subarray(100));
  assert.equal(auth.getPending().length, 0);
  connection.close();
  await assert.rejects(connection.request('directory', { path: '' }), /关闭|断开/);
});

test('native SSH prompts for a first host key and password without writing credentials to project config', { timeout: 30000 }, async t => {
  const fixture = await createSSHFixture({ password: true, unknownHost: true, nativeWorker: false });
  const askpassPath = process.platform === 'win32' ? path.join(fixture.directory, 'askpass.exe') : undefined;
  if (askpassPath) await fs.copyFile(path.join(integrationDir, 'ssh-askpass.exe'), askpassPath);
  const prompts = [];
  const auth = await new SSHAuthServer(queue => {
    const prompt = queue[0];
    if (!prompt) return;
    prompts.push(prompt.kind);
    setImmediate(() => auth.answer(prompt.id, prompt.kind === 'confirm' ? 'yes' : fixture.secret));
  }).start();
  const connection = new RemoteConnection({ id: randomUUID(), kind: 'ssh', path: '/srv/fixture', ssh: { host: 'fixture', configFile: fixture.configFile } }, { integrationDir, auth, sshPath, askpassPath, sessionKey: 'test-auth-key' });
  t.after(async () => { connection.close(); auth.close(); await fixture.close(); });
  await connection.ready;
  assert.ok(prompts.includes('confirm'));
  assert.ok(prompts.includes('secret'));
  assert.ok(!(await fs.readFile(fixture.configFile, 'utf8')).includes(fixture.secret));
  assert.ok((await fs.readFile(fixture.knownHosts, 'utf8')).trim().length > 0);
});

test('untrusted askpass requests are rejected without displaying a credential prompt', async t => {
  const auth = await new SSHAuthServer().start();
  t.after(() => auth.close());
  auth.register('test-project', 'fixture', () => {});
  const response = await fetch(auth.url, { method: 'POST', headers: { Authorization: 'Bearer wrong', 'Content-Type': 'application/json' }, body: JSON.stringify({ connectionId: 'test-project', prompt: 'password' }) });
  assert.equal(response.status, 403);
  assert.equal(auth.getPending().length, 0);
});

test('Linux remote worker reads real files, enforces boundaries and emits Codex completion', { timeout: 40000, skip: process.platform === 'win32' }, async t => {
  const fixture = await createSSHFixture({ nativeWorker: true });
  const auth = await new SSHAuthServer().start();
  const project = { id: randomUUID(), kind: 'ssh', path: fixture.project, ssh: { host: 'fixture', configFile: fixture.configFile } };
  const events = []; let output = '';
  await fs.writeFile(path.join(fixture.project, 'hello.txt'), '中文 remote file');
  await fs.copyFile(path.join(__dirname, '..', 'assets', 'icon.png'), path.join(fixture.project, 'image.png'));
  await fs.writeFile(path.join(fixture.project, 'page.html'), '<h1>Remote preview</h1>');
  await fs.writeFile(path.join(fixture.project, 'README.md'), '# SSH Markdown');
  const stub = '#!/usr/bin/env python3\nimport json,subprocess,sys\ncommand=json.loads(sys.argv[2][7:])\nsubprocess.run(command+[json.dumps({"type":"agent-turn-complete","thread-id":"test","turn-id":"1"})])\nprint("REMOTE_CODEX_DONE")\n';
  await fs.writeFile(path.join(fixture.home, 'bin', 'codex'), stub, { mode: 0o755 });
  const connection = new RemoteConnection(project, { integrationDir, auth, sshPath, sessionKey: 'test-linux-key', onEvent: event => events.push(event) });
  connection.onData(data => { output += data; });
  t.after(async () => { connection.close(); auth.close(); await fixture.close(); });
  await connection.ready;
  assert.equal((await connection.request('preview', { path: 'hello.txt', page: 0 })).content, '中文 remote file');
  assert.equal((await connection.request('preview', { path: 'image.png', page: 0 })).kind, 'image');
  assert.equal((await connection.request('preview', { path: 'page.html', page: 0 })).kind, 'html');
  assert.equal((await connection.request('preview', { path: 'README.md', page: 0 })).kind, 'markdown');
  assert.equal(Buffer.from(await connection.request('read', { path: 'hello.txt', offset: 0, length: 6 }), 'base64').toString(), '中文');
  const editable = await connection.request('preview', { path: 'hello.txt', page: 0 });
  const edited = await connection.request('save-file', { path: 'hello.txt', page: 0, revision: editable.revision, data: Buffer.from('通过 SSH 保存\n第二行', 'utf8').toString('base64') });
  assert.equal(edited.content, '通过 SSH 保存\n第二行');
  assert.equal(await fs.readFile(path.join(fixture.project, 'hello.txt'), 'utf8'), edited.content);
  await assert.rejects(connection.request('save-file', { path: 'hello.txt', page: 0, revision: editable.revision, data: Buffer.from('stale').toString('base64') }), /其他程序修改/);
  await assert.rejects(connection.request('read', { path: '../outside', offset: 0, length: 10 }));
  await waitFor(() => events.some(event => event.type === 'shell-prompt' && event.codexAvailable));
  connection.write('printf FIRST > shift-first.txt');
  connection.write('\x1b[13;2u');
  connection.write('printf SECOND > shift-second.txt');
  await new Promise(resolve => setTimeout(resolve, 150));
  await assert.rejects(fs.stat(path.join(fixture.project, 'shift-first.txt')), 'modified Enter must not execute the first complete Bash command');
  connection.write('\r');
  await waitFor(async () => fs.readFile(path.join(fixture.project, 'shift-second.txt'), 'utf8').then(value => value === 'SECOND', () => false));
  assert.equal(await fs.readFile(path.join(fixture.project, 'shift-first.txt'), 'utf8'), 'FIRST');
  connection.write('codex\r');
  await waitFor(() => events.some(event => event.type === 'turn-complete'));
  const activityThread = randomUUID(), activitySince = Date.now();
  const sessions = path.join(fixture.home, '.codex', 'sessions');
  await fs.mkdir(sessions, { recursive: true });
  const activityFile = path.join(sessions, `rollout-${activityThread}.jsonl`);
  const activityRecord = type => JSON.stringify({ type: 'event_msg', timestamp: new Date().toISOString(), payload: { type, turn_id: 'parent-turn' } }) + '\n';
  await fs.writeFile(activityFile, JSON.stringify({ type: 'session_meta', payload: { id: activityThread, cwd: fixture.project, source: 'cli' } }) + '\n' + activityRecord('task_started'));
  assert.equal((await connection.request('codex-status', { since: activitySince })).state, 'working');
  await fs.appendFile(activityFile, activityRecord('task_complete'));
  assert.equal((await connection.request('codex-status', { since: activitySince })).state, 'complete');
  await waitFor(() => events.some(event => event.type === 'codex-exited'));
  assert.ok(output.includes('REMOTE_CODEX_DONE'));
  let clipboard = [];
  const operations = new FileOperations({ cacheRoot: path.join(fixture.directory, 'clipboard-cache'), remote: () => connection,
    clipboard: async (action, paths) => action === 'copy' ? (clipboard = paths) : clipboard, confirmDelete: async () => true,
  });
  await operations.create(project, '', '上传目录', 'directory');
  await operations.create(project, '上传目录', 'empty.txt', 'file');
  await operations.rename(project, '上传目录/empty.txt', 'renamed.txt');
  const source = path.join(fixture.directory, 'upload.bin'); const payload = Buffer.alloc(1024 * 1024 + 11, 73);
  await fs.writeFile(source, payload); clipboard = [source];
  const pasted = await operations.paste(project, '上传目录');
  assert.deepEqual(pasted.pasted, ['上传目录/upload.bin']);
  assert.deepEqual(await fs.readFile(path.join(fixture.project, '上传目录/upload.bin')), payload);
  await operations.copy(project, ['上传目录']);
  assert.deepEqual(await fs.readFile(path.join(clipboard[0], 'upload.bin')), payload);
  await operations.remove(project, ['上传目录']);
  await assert.rejects(fs.stat(path.join(fixture.project, '上传目录')));
  assert.deepEqual(await fs.readFile(source), payload);
});
