const { contextBridge, ipcRenderer } = require('electron');
const listen = (channel, callback) => {
  const listener = (_event, data) => callback(data);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};

contextBridge.exposeInMainWorld('projectGrid', {
  getState: () => ipcRenderer.invoke('workspace:state'),
  getUpdateState: () => ipcRenderer.invoke('updates:state'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  openDownloadPage: () => ipcRenderer.invoke('updates:download-page'),
  onUpdateState: callback => listen('updates:changed', callback),
  addProjects: () => ipcRenderer.invoke('workspace:add'),
  addSSHProject: input => ipcRenderer.invoke('workspace:add-ssh', input),
  getSSHInfo: () => ipcRenderer.invoke('ssh:info'),
  getSSHAuth: () => ipcRenderer.invoke('ssh:auth-pending'),
  answerSSHAuth: (id, answer) => ipcRenderer.invoke('ssh:auth-answer', id, answer),
  onSSHAuth: callback => listen('ssh:auth-changed', callback),
  removeProject: id => ipcRenderer.invoke('workspace:remove', id),
  swapProjects: (source, target) => ipcRenderer.invoke('workspace:swap', source, target),
  reorderProjects: ids => ipcRenderer.invoke('workspace:reorder', ids),
  acknowledge: id => ipcRenderer.invoke('workspace:acknowledge', id),
  acknowledgeAll: () => ipcRenderer.invoke('workspace:acknowledge-all'),
  settings: patch => ipcRenderer.invoke('workspace:settings', patch),
  listDirectory: (id, relativePath = '', offset = 0) => ipcRenderer.invoke('project:directory', id, relativePath, offset),
  gitStatus: id => ipcRenderer.invoke('project:git-status', id),
  gitHistory: (id, offset = 0) => ipcRenderer.invoke('project:git-history', id, offset),
  gitFiles: (id, hash) => ipcRenderer.invoke('project:git-files', id, hash),
  createEntry: (id, directory, name, kind) => ipcRenderer.invoke('project:create-entry', id, directory, name, kind),
  renameEntry: (id, relative, name) => ipcRenderer.invoke('project:rename-entry', id, relative, name),
  deleteEntries: (id, paths) => ipcRenderer.invoke('project:delete-entries', id, paths),
  copyEntries: (id, paths) => ipcRenderer.invoke('project:copy-entries', id, paths),
  copyPaths: (id, paths, format) => ipcRenderer.invoke('project:copy-paths', id, paths, format),
  pasteEntries: (id, directory) => ipcRenderer.invoke('project:paste-entries', id, directory),
  fileTreeFocus: (id, focused) => ipcRenderer.send('files:focus', id, focused),
  getFileProgress: () => ipcRenderer.invoke('files:progress'),
  onFileProgress: callback => listen('files:progress', callback),
  cancelFileOperation: () => ipcRenderer.invoke('files:cancel'),
  getVoiceState: () => ipcRenderer.invoke('voice:state'),
  prepareVoice: () => ipcRenderer.invoke('voice:prepare'),
  cancelVoice: (mode = 'recognition') => ipcRenderer.invoke('voice:cancel', mode),
  transcribe: (audio, language) => ipcRenderer.invoke('voice:transcribe', audio, language),
  onVoiceState: callback => listen('voice:state', callback),
  pasteTerminal: (id, text, sessionId) => ipcRenderer.invoke('terminal:paste', id, text, sessionId),
  onTerminalPaste: callback => listen('terminal:paste', callback),
  readFile: (id, relativePath, pageIndex = 0) => ipcRenderer.invoke('project:file', id, relativePath, pageIndex),
  saveFile: (id, relativePath, pageIndex, revision, content) => ipcRenderer.invoke('project:save-file', id, relativePath, pageIndex, revision, content),
  confirmEditorClose: filename => ipcRenderer.invoke('editor:confirm-close', filename),
  editorDirty: (dirty, id, filename) => ipcRenderer.send('editor:dirty', dirty, id, filename),
  onEditorClose: callback => listen('editor:request-close', callback),
  editorCloseResult: (id, accepted) => ipcRenderer.send('editor:close-result', id, accepted),
  closePreview: id => ipcRenderer.invoke('project:preview-close', id),
  openLink: (id, target) => ipcRenderer.invoke('project:open-link', id, target),
  openVideo: (id, relativePath) => ipcRenderer.invoke('project:open-video', id, relativePath),
  revealProject: id => ipcRenderer.invoke('project:reveal', id),
  startTerminal: id => ipcRenderer.invoke('terminal:start', id),
  addTerminal: id => ipcRenderer.invoke('terminal:add', id),
  closeTerminal: id => ipcRenderer.invoke('terminal:close', id),
  restartTerminal: id => ipcRenderer.invoke('terminal:restart', id),
  attachTerminal: id => ipcRenderer.invoke('terminal:attach', id),
  launchCodex: id => ipcRenderer.invoke('terminal:codex', id),
  writeTerminal: (id, data) => ipcRenderer.send('terminal:write', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('terminal:resize', id, cols, rows),
  copy: text => ipcRenderer.invoke('clipboard:copy', text),
  readClipboard: () => ipcRenderer.invoke('clipboard:read'),
  terminalFocus: (id, focused) => ipcRenderer.send('terminal:focus', id, focused),
  onState: callback => listen('workspace:changed', callback),
  onTerminalData: callback => listen('terminal:data', callback),
  onFocusProject: callback => listen('project:focus', callback),
  onError: callback => listen('app:error', callback),
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  focusMode: enabled => ipcRenderer.send('window:focus-mode', enabled),
  quit: () => ipcRenderer.invoke('app:quit'),
});
