const { contextBridge, ipcRenderer } = require('electron');
const listen = (channel, callback) => {
  const listener = (_event, data) => callback(data);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};

contextBridge.exposeInMainWorld('projectGrid', {
  getState: () => ipcRenderer.invoke('workspace:state'),
  getUpdateState: () => ipcRenderer.invoke('updates:state'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  openDownloadPage: () => ipcRenderer.invoke('updates:download-page'),
  onUpdateState: callback => listen('updates:changed', callback),
  addProjects: () => ipcRenderer.invoke('workspace:add'),
  addSSHProject: input => ipcRenderer.invoke('workspace:add-ssh', input),
  getSSHInfo: () => ipcRenderer.invoke('ssh:info'),
  getSSHAuth: () => ipcRenderer.invoke('ssh:auth-pending'),
  answerSSHAuth: (id, answer) => ipcRenderer.invoke('ssh:auth-answer', id, answer),
  onSSHAuth: callback => listen('ssh:auth-changed', callback),
  removeProject: id => ipcRenderer.invoke('workspace:remove', id),
  swapProjects: (source, target) => ipcRenderer.invoke('workspace:swap', source, target),
  acknowledge: id => ipcRenderer.invoke('workspace:acknowledge', id),
  markDone: (id, done) => ipcRenderer.invoke('workspace:done', id, done),
  acknowledgeAll: () => ipcRenderer.invoke('workspace:acknowledge-all'),
  settings: patch => ipcRenderer.invoke('workspace:settings', patch),
  openInCode: (id, relativePath) => ipcRenderer.invoke('project:code', id, relativePath),
  listDirectory: (id, relativePath = '', offset = 0) => ipcRenderer.invoke('project:directory', id, relativePath, offset),
  readFile: (id, relativePath, pageIndex = 0) => ipcRenderer.invoke('project:file', id, relativePath, pageIndex),
  closePreview: id => ipcRenderer.invoke('project:preview-close', id),
  openLink: (id, target) => ipcRenderer.invoke('project:open-link', id, target),
  openVideo: (id, relativePath) => ipcRenderer.invoke('project:open-video', id, relativePath),
  revealProject: id => ipcRenderer.invoke('project:reveal', id),
  startTerminal: id => ipcRenderer.invoke('terminal:start', id),
  restartTerminal: id => ipcRenderer.invoke('terminal:restart', id),
  attachTerminal: id => ipcRenderer.invoke('terminal:attach', id),
  launchCodex: id => ipcRenderer.invoke('terminal:codex', id),
  writeTerminal: (id, data) => ipcRenderer.send('terminal:write', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('terminal:resize', id, cols, rows),
  copy: text => ipcRenderer.invoke('clipboard:copy', text),
  readClipboard: () => ipcRenderer.invoke('clipboard:read'),
  terminalFocus: (id, focused) => ipcRenderer.send('terminal:focus', id, focused),
  onState: callback => listen('workspace:changed', callback),
  onTerminalData: callback => listen('terminal:data', callback),
  onFocusProject: callback => listen('project:focus', callback),
  onError: callback => listen('app:error', callback),
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  focusMode: enabled => ipcRenderer.send('window:focus-mode', enabled),
  quit: () => ipcRenderer.invoke('app:quit'),
});
