import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { _electron as electron } from 'playwright';

const require = createRequire(import.meta.url), root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { createSSHFixture } = require('../tests/helpers/ssh-fixture.cjs');
const ssh = await createSSHFixture({ nativeWorker: false });
const output = path.join(root, '.test-output', `navigation-${Date.now()}`), profile = path.join(output, 'profile');
const local = { id: randomUUID(), name: '本地项目', path: path.join(output, 'local'), restore: { terminal: true, codex: false } };
const remote = { id: randomUUID(), name: '远程项目', kind: 'ssh', path: '/srv/fixture', ssh: { host: 'fixture', configFile: ssh.configFile }, restore: { terminal: false, codex: false } };
const legacy = { id: randomUUID(), name: '旧版完成项目', path: path.join(output, 'legacy'), done: true, restore: { terminal: true, codex: true }, terminals: [{ id: randomUUID(), restore: { terminal: true, codex: true } }] };
const closed = { id: randomUUID(), name: '已关闭主终端', path: path.join(output, 'closed'), done: true, restore: { terminal: false, codex: false }, terminals: [{ id: randomUUID(), restore: { terminal: true, codex: true } }] };
await fs.mkdir(profile, { recursive: true }); await fs.mkdir(local.path);
await fs.mkdir(legacy.path); await fs.mkdir(closed.path);
await fs.writeFile(path.join(local.path, 'unsupported.txt'), Buffer.from([0xff, 0xff, 0xff]));
await fs.mkdir(path.join(ssh.project, 'docs/nested'), { recursive: true });
await fs.writeFile(path.join(ssh.project, 'docs/nested/note.txt'), 'REMOTE_DIRECTORY_READY');
await fs.symlink(path.join(ssh.project, 'docs/nested'), path.join(ssh.project, 'docs-alias'), 'junction');
await fs.writeFile(path.join(ssh.project, 'README.md'), '# 远程文件\n\n[查看文档目录](docs/nested/)\n');
// A regular shell at the end proves startup restoration actually ran after any legacy entries.
await fs.writeFile(path.join(profile, 'workspace.json'), JSON.stringify({ version: 2, projects: [legacy, closed, remote, local], settings: { notifications: false, restoreSessions: true, closeToTray: false } }));
const env = { ...process.env, PROJECT_GRID_DATA_DIR: profile, PROJECT_GRID_TEST_SSH_CONFIG: ssh.configFile, PROJECT_GRID_TEST_RESTORE: '1', CODEX_HOME: path.join(output, 'codex-home') }; delete env.ELECTRON_RUN_AS_NODE; delete env.PROJECT_GRID_DEV_URL;
const packaged = process.argv.includes('--packaged'); let app, page;
const state = async () => (await page.evaluate(() => window.projectGrid.getState())).value;
async function waitFor(check, label) { const until = Date.now() + 20000; while (Date.now() < until) { if (await check()) return; await new Promise(resolve => setTimeout(resolve, 70)); } throw new Error(`Timed out: ${label}`); }
const settled = focused => page.waitForFunction(focused => !!document.querySelector('.focus-mode') === focused && !document.querySelector('[data-focus-motion]'), focused);
const errors = [];
try {
  app = await electron.launch({ executablePath: packaged ? path.join(root, 'release/win-unpacked/Project Grid.exe') : require('electron'), args: packaged ? [] : [root], cwd: root, env });
  page = await app.firstWindow(); page.on('pageerror', error => errors.push(error.message));
  await app.evaluate(({ shell, dialog }) => {
    globalThis.navigationOpened = []; globalThis.editorCloseReply = 2;
    shell.openPath = async target => { globalThis.navigationOpened.push(target); return ''; };
    shell.openExternal = async target => { globalThis.navigationOpened.push(target); };
    dialog.showMessageBox = async (_window, options) => ({ response: options.title === '未保存的修改' ? globalThis.editorCloseReply : 1 });
  });
  await page.waitForSelector('.project-panel');
  await waitFor(async () => (await state()).projects.find(project => project.id === local.id).shellReady, 'ordinary shell restores while legacy-finished terminals remain stopped');
  const migrated = (await state()).projects.find(project => project.id === legacy.id);
  assert.deepEqual(migrated.terminals.map(terminal => terminal.id), [legacy.id, legacy.terminals[0].id]);
  assert.ok(migrated.terminals.every(terminal => !terminal.sessionId && terminal.status === 'stopped'));
  assert.deepEqual((await state()).projects.find(project => project.id === closed.id).terminals.map(terminal => terminal.id), [closed.terminals[0].id], 'previously closed primary does not reappear');
  const legacyPanel = page.locator(`[data-project-id="${legacy.id}"]`);
  await legacyPanel.getByRole('button', { name: `全屏查看 ${legacy.name}`, exact: true }).click(); await settled(true);
  await page.screenshot({ path: path.join(output, 'legacy-stopped-splits.png') });
  await legacyPanel.locator(`[data-terminal-id="${legacy.id}"]`).getByRole('button', { name: '启动终端', exact: true }).click();
  await waitFor(async () => (await state()).projects.find(project => project.id === legacy.id).terminals[0].shellReady, 'migrated primary can start manually');
  const started = (await state()).projects.find(project => project.id === legacy.id);
  assert.equal(started.terminals.length, 2); assert.equal(started.terminals[0].codexActive, false); assert.equal(started.terminals[1].sessionId, null);
  assert.deepEqual(await page.evaluate(id => window.projectGrid.closeTerminal(id), legacy.id), { ok: true, value: true });
  await waitFor(async () => (await state()).projects.find(project => project.id === legacy.id).terminals.length === 1, 'explicitly closing a primary still removes its pane');
  await page.getByRole('button', { name: '返回总览', exact: true }).click(); await settled(false);
  assert.deepEqual(await page.evaluate(() => ['openInCode', 'markDone'].filter(key => key in window.projectGrid)), []);
  const first = page.locator(`[data-project-id="${local.id}"]`), second = page.locator(`[data-project-id="${remote.id}"]`);
  await first.getByRole('button', { name: `${local.name} 的更多操作`, exact: true }).click();
  assert.equal(await page.getByRole('menuitem', { name: /VS Code|标记开发完成|继续开发/ }).count(), 0);
  await page.getByRole('menuitem', { name: '打开项目目录', exact: true }).click();
  assert.deepEqual(await app.evaluate(() => globalThis.navigationOpened), [local.path]);
  await first.getByRole('button', { name: `全屏查看 ${local.name}`, exact: true }).click(); await settled(true);
  const sidebar = page.getByRole('complementary', { name: '项目侧边栏' });
  assert.deepEqual(await sidebar.locator('.explorer-actions button').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label'))), ['Git 历史']);
  await page.screenshot({ path: path.join(output, 'sidebar.png') });
  await page.keyboard.press('Control+b'); await sidebar.getByRole('button', { name: '展开目录栏', exact: true }).waitFor();
  assert.equal(await sidebar.locator('.explorer-actions button').count(), 1);
  await page.screenshot({ path: path.join(output, 'sidebar-collapsed.png') });
  await page.keyboard.press('Control+b');
  await page.getByRole('treeitem', { name: 'unsupported.txt', exact: true }).click();
  await page.getByText('暂不支持此文件的文本编码。', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: /VS Code|标记开发完成/ }).count(), 0);
  await page.screenshot({ path: path.join(output, 'unsupported.png') });
  await page.getByRole('button', { name: '返回总览', exact: true }).click(); await settled(false);
  await second.getByRole('button', { name: '启动终端', exact: true }).click();
  await waitFor(async () => (await state()).projects.find(project => project.id === remote.id).shellReady, 'real SSH transport ready');
  const sessionId = (await state()).projects.find(project => project.id === remote.id).sessionId;
  await second.getByRole('button', { name: `${remote.name} 的更多操作`, exact: true }).click();
  await page.getByRole('menuitem', { name: '打开项目目录', exact: true }).click(); await settled(true);
  await page.getByRole('treeitem', { name: 'README.md', exact: true }).waitFor();
  await page.getByRole('button', { name: '返回总览', exact: true }).click(); await settled(false);
  for (const target of ['/srv/fixture/docs/nested', '/srv/fixture/docs-alias']) {
    // The SSH fixture echoes through the real transport, including this OSC-8 link.
    await page.evaluate(({ id, target }) => window.projectGrid.writeTerminal(id, `\x1b[2J\x1b[H\x1b]8;;${target}\x07REMOTE_DOCS_LINK\x1b]8;;\x07\r\n`), { id: remote.id, target });
    const link = second.locator('.xterm-rows').getByText('REMOTE_DOCS_LINK', { exact: true });
    await link.waitFor();
    const box = await link.boundingBox(), screen = second.locator('.xterm-screen'), screenBox = await screen.boundingBox();
    const position = { x: box.x - screenBox.x + 20, y: box.y - screenBox.y + box.height / 2 };
    await screen.hover({ position: { x: position.x + 30, y: position.y + 25 } });
    await screen.hover({ position });
    await waitFor(async () => second.locator('.terminal-host').getAttribute('title').then(title => title?.includes(target)), 'terminal link hover ready');
    await screen.click({ position, modifiers: ['Control'] });
    await settled(true);
    await page.getByRole('treeitem', { name: 'note.txt', exact: true }).waitFor();
    assert.equal(await page.getByRole('treeitem', { name: 'nested', exact: true }).getAttribute('aria-expanded'), 'true');
    await page.screenshot({ path: path.join(output, target.endsWith('docs-alias') ? 'ssh-link-alias.png' : 'ssh-link-directory.png') });
    await page.getByRole('button', { name: '返回总览', exact: true }).click(); await settled(false);
  }
  await second.getByRole('button', { name: `全屏查看 ${remote.name}`, exact: true }).click(); await settled(true);
  await page.getByRole('treeitem', { name: 'README.md', exact: true }).click();
  const editor = page.getByRole('textbox', { name: '文件编辑器', exact: true });
  await editor.fill('# 未保存草稿\n\n[查看文档目录](docs/nested/)\n');
  await page.getByRole('button', { name: '预览', exact: true }).click();
  await page.getByRole('link', { name: '查看文档目录', exact: true }).click();
  assert.ok(await page.getByRole('heading', { name: '未保存草稿', exact: true }).isVisible(), 'cancel keeps the unsaved Markdown draft');
  await app.evaluate(() => { globalThis.editorCloseReply = 1; });
  await page.getByRole('link', { name: '查看文档目录', exact: true }).click();
  await page.locator('.file-preview').waitFor({ state: 'detached' });
  await page.getByRole('treeitem', { name: 'note.txt', exact: true }).waitFor();
  assert.equal((await state()).projects.find(project => project.id === remote.id).sessionId, sessionId);
  assert.deepEqual(await app.evaluate(() => globalThis.navigationOpened), [local.path], 'remote navigation never opens an external app');
  const rejected = await page.evaluate(id => window.projectGrid.openLink(id, 'vscode://file/example'), remote.id); assert.equal(rejected.ok, false);
  await page.evaluate(id => window.projectGrid.openLink(id, 'https://example.com/docs'), local.id);
  assert.deepEqual(await app.evaluate(() => globalThis.navigationOpened), [local.path, 'https://example.com/docs']);
  assert.deepEqual(errors, []);
  console.log(`PASS: removed sidebar/manual-finish/VS Code actions, local folder/browser retained, SSH root/nested/symlink/Markdown directories stay internal and protect drafts. Screenshots: ${output}`);
} catch (error) { if (page) await page.screenshot({ path: path.join(output, 'failure.png') }).catch(() => {}); throw error; }
finally { if (app) await app.close(); await ssh.close(); }
