export type Result<T> = { ok: true; value: T } | { ok: false; error: string };
export type Project = {
  id: string; name: string; path: string; branch: string; unread: number; done: boolean;
  kind: 'local' | 'ssh'; ssh: { host: string; configFile: string | null } | null;
  lastCompletedAt: number | null; lastActivityAt: number | null; awaitingCompletion: boolean;
  sessionId: string | null; status: 'stopped' | 'starting' | 'shell' | 'codex' | 'exited';
  codexActive: boolean; codexActivity: 'unknown' | 'working' | 'complete' | 'interrupted'; shellReady: boolean; codexAvailable: boolean | null; error: string | null;
};
export type Settings = { columns: number; notifications: boolean; sound: boolean; closeToTray: boolean; explorerCollapsed: boolean; fontSize: number; restoreSessions: boolean; focusAnimation: 'smooth' | 'system' | 'off' };
export type SSHInfo = { hosts: string[]; configFile: string; configExists: boolean; sshPath: string; source: string };
export type SSHAuthPrompt = { id: string; host: string; message: string; kind: 'secret' | 'confirm' };
export type Workspace = { projects: Project[]; settings: Settings; warning: string | null; platform: string; version: string };
export type TerminalSnapshot = { sessionId: string | null; seq: number; data: string };
export type TerminalPacket = TerminalSnapshot & { id: string };
export type FileEntry = { name: string; path: string; kind: 'directory' | 'file' | 'link' };
export type FileProgress = { projectId: string; text: string } | null;
export type VoiceState = { phase: 'missing' | 'downloading' | 'ready' | 'transcribing' | 'error'; ready: boolean; percent: number; error: string | null; model: string; downloadBytes: number };
export type DirectoryListing = { path: string; entries: FileEntry[]; total: number; nextOffset: number | null };
export type TextPage = { index: number; count: number; byteStart: number; byteEnd: number; encoding: string };
export type AppUpdateState = { supported: boolean; currentVersion: string; status: 'unavailable' | 'idle' | 'checking' | 'current' | 'downloading' | 'ready' | 'error'; version: string | null; percent: number; error: string | null };
export type FilePreview = { path: string; name: string; size: number; modifiedAt: number } & (
  { kind: 'text'; content: string; page: TextPage } | { kind: 'unsupported'; reason: string }
  | { kind: 'image' | 'video'; mimeType: string; url: string; previewId: string }
  | { kind: 'html'; content: string; page: TextPage; url: string; previewId: string }
);
export type Bridge = {
  getState(): Promise<Result<Workspace>>;
  getUpdateState(): Promise<Result<AppUpdateState>>;
  checkForUpdates(): Promise<Result<AppUpdateState>>;
  installUpdate(): Promise<Result<boolean>>;
  openDownloadPage(): Promise<Result<void>>;
  onUpdateState(callback: (state: AppUpdateState) => void): () => void;
  addProjects(): Promise<Result<string[]>>;
  addSSHProject(input: { host: string; path: string; name?: string }): Promise<Result<string>>;
  getSSHInfo(): Promise<Result<SSHInfo>>;
  getSSHAuth(): Promise<Result<SSHAuthPrompt[]>>;
  answerSSHAuth(id: string, answer: string | null): Promise<Result<void>>;
  onSSHAuth(callback: (prompts: SSHAuthPrompt[]) => void): () => void;
  removeProject(id: string): Promise<Result<boolean>>;
  swapProjects(source: string, target: string): Promise<Result<void>>;
  reorderProjects(ids: string[]): Promise<Result<void>>;
  acknowledge(id: string): Promise<Result<void>>;
  markDone(id: string, done: boolean): Promise<Result<void>>;
  acknowledgeAll(): Promise<Result<void>>;
  settings(patch: Partial<Settings>): Promise<Result<void>>;
  openInCode(id: string, relativePath?: string): Promise<Result<void>>;
  listDirectory(id: string, relativePath?: string, offset?: number): Promise<Result<DirectoryListing>>;
  createEntry(id: string, directory: string, name: string, kind: 'file' | 'directory'): Promise<Result<{ path: string; kind: string }>>;
  renameEntry(id: string, relative: string, name: string): Promise<Result<{ path: string }>>;
  deleteEntries(id: string, paths: string[]): Promise<Result<{ deleted: string[] }>>;
  copyEntries(id: string, paths: string[]): Promise<Result<{ count: number }>>;
  pasteEntries(id: string, directory: string): Promise<Result<{ pasted: string[] }>>;
  fileTreeFocus(id: string, focused: boolean): void;
  getFileProgress(): Promise<Result<FileProgress>>;
  onFileProgress(callback: (progress: FileProgress) => void): () => void;
  cancelFileOperation(): Promise<Result<void>>;
  getVoiceState(): Promise<Result<VoiceState>>;
  prepareVoice(): Promise<Result<VoiceState>>;
  cancelVoice(mode?: 'download' | 'recognition'): Promise<Result<void>>;
  transcribe(audio: ArrayBuffer, language: string): Promise<Result<string>>;
  onVoiceState(callback: (state: VoiceState) => void): () => void;
  pasteTerminal(id: string, text: string, sessionId: string): Promise<Result<void>>;
  onTerminalPaste(callback: (packet: { id: string; sessionId: string; text: string }) => void): () => void;
  readFile(id: string, relativePath: string, pageIndex?: number): Promise<Result<FilePreview>>;
  closePreview(id: string): Promise<Result<void>>;
  openLink(id: string, target: string): Promise<Result<{ kind: 'external' } | { kind: 'file'; path: string }>>;
  openVideo(id: string, relativePath: string): Promise<Result<void>>;
  revealProject(id: string): Promise<Result<void>>;
  startTerminal(id: string): Promise<Result<void>>;
  restartTerminal(id: string): Promise<Result<boolean>>;
  attachTerminal(id: string): Promise<Result<TerminalSnapshot>>;
  launchCodex(id: string): Promise<Result<void>>;
  writeTerminal(id: string, data: string): void;
  resizeTerminal(id: string, cols: number, rows: number): void;
  copy(text: string): Promise<Result<void>>;
  readClipboard(): Promise<Result<string>>;
  terminalFocus(id: string, focused: boolean): void;
  onState(callback: (state: Workspace) => void): () => void;
  onTerminalData(callback: (packet: TerminalPacket) => void): () => void;
  onFocusProject(callback: (id: string) => void): () => void;
  onError(callback: (message: string) => void): () => void;
  minimize(): void; maximize(): void; close(): void; focusMode(enabled: boolean): void;
  quit(): Promise<Result<boolean>>;
};
declare global { interface Window { projectGrid: Bridge; } }
